//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartcartapisnew.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class smartcartdbEntities7 : DbContext
    {
        public smartcartdbEntities7()
            : base("name=smartcartdbEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cart> carts { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<receipt> receipts { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<userr> userrs { get; set; }
    
        public virtual ObjectResult<GET_RECEIPTS_Result> GET_RECEIPTS(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_RECEIPTS_Result>("GET_RECEIPTS", user_idParameter);
        }
    
        public virtual ObjectResult<LOGIN_USER_Result> LOGIN_USER(string email, string pass)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOGIN_USER_Result>("LOGIN_USER", emailParameter, passParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> NEW_RECEIPT(Nullable<int> user_id, string date, Nullable<double> total)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NEW_RECEIPT", user_idParameter, dateParameter, totalParameter);
        }
    
        public virtual ObjectResult<RETURN_PRODUCT_Result> RETURN_PRODUCT(Nullable<long> barcode)
        {
            var barcodeParameter = barcode.HasValue ?
                new ObjectParameter("barcode", barcode) :
                new ObjectParameter("barcode", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RETURN_PRODUCT_Result>("RETURN_PRODUCT", barcodeParameter);
        }
    
        public virtual int SIGNUP_USER(string name, string email, string password)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SIGNUP_USER", nameParameter, emailParameter, passwordParameter);
        }
    }
}
