//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartcartapisnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipt
    {
        public receipt()
        {
            this.carts = new HashSet<cart>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string date { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual ICollection<cart> carts { get; set; }
        public virtual userr userr { get; set; }
    }
}
